use_frameworks!

platform :ios, '9.0'

target 'MyFirstLabLibrary_Example' do
  pod 'MyFirstLabLibrary', :path => '../'

  target 'MyFirstLabLibrary_Tests' do
    inherit! :search_paths

    
  end
end
